routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\LoginController;
use App\Http\Controllers\PanelController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\SupervisorController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\ClientController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [LoginController::class, 'index'])->name('login')->middleware('web');
Route::post('login/submit', [LoginController::class, 'login_submit'])->name('login.submit')->middleware('guest:admin');

Route::group(['middleware' => 'auth:admin'], function () {

    Route::get('logout', function () {
        Auth::logout();
        return redirect('/');
    })->name('logout');


    Route::get('dashboard', [PanelController::class, 'index'])->name('dashboard');
    Route::get('project', [ProjectController::class, 'index'])->name('project.index');
    Route::post('project/store', [ProjectController::class, 'store'])->name('project.store');
    Route::post('project/status_change', [ProjectController::class, 'status_change'])->name('project.status_change');
    Route::delete('project/delete/{id}', [ProjectController::class, 'destroy'])->name('project.delete');
    Route::get('project/edit/{id}', [ProjectController::class, 'edit'])->name('project.edit');
    Route::post('project/update/{id}', [ProjectController::class, 'update'])->name('project.update');

    Route::get('task', [TaskController::class, 'index'])->name('task.index');
    Route::post('task/store', [TaskController::class, 'store'])->name('task.store');
    Route::post('task/status_change', [TaskController::class, 'status_change'])->name('task.status_change');
    Route::delete('task/delete/{id}', [TaskController::class, 'destroy'])->name('task.delete');
    Route::get('task/edit/{id}', [TaskController::class, 'edit'])->name('task.edit');
    Route::post('task/update/{id}', [TaskController::class, 'update'])->name('task.update');

    Route::get('task/complete/{id}', [TaskController::class, 'complete'])->name('task.complete');
    Route::post('task/complete_submit/{id}', [TaskController::class, 'complete_submit'])->name('task.complete_submit');

    Route::post('fetch-members', [TaskController::class, 'fetchMember']);

    Route::resource('supervisor', SupervisorController::class);
    Route::post('supervisor/status_change', [SupervisorController::class, 'status_change'])->name('supervisor.status_change');

    Route::resource('staff', StaffController::class);
    Route::post('staff/status_change', [StaffController::class, 'status_change'])->name('staff.status_change');

    Route::resource('client', ClientController::class);
    Route::post('client/status_change', [ClientController::class, 'status_change'])->name('client.status_change');

    // Route::resources([
    //     'project' => 'ProjectController',
    // ]);
});

resources/views/common/footer.blade.php
<div class="float-right d-none d-sm-block">

</div>
<strong>Copyright &copy; {{ date('Y') }} <a href="https://mobotics.in">Mobotics</a>.</strong> All rights reserved.

resources/views/common/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        @if (isset(auth()->user()->id))
            <li class="nav-item">
                <a href="{{ route('logout') }}" class="nav-link">Logout</a>
            </li>
        @endif
    </ul>
</nav>

resources/views/common/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Management System</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- IonIcons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets/dist/css/adminlte.min.css') }}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
        crossorigin="anonymous" />

    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
    <style>
        .select2-container .select2-selection--single {
            box-sizing: border-box;
            cursor: pointer;
            display: block;
            height: 38px !important;
            user-select: none;
            -webkit-user-select: none;
        }

        .select2-container--default .select2-selection--single .select2-selection__arrow {
            height: 38px !important;
            position: absolute;
            top: 1px;
            right: 1px;
            width: 20px;
        }
    </style>
    @stack('styles')
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar-->
        <header class="app-header">
            @include('common.header')
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            @include('common.navigation')
        </aside>
        <main class="app-content">
            @stack('actions')
            @yield('content')
        </main>
        <footer class="main-footer">
            @include('common.footer')
        </footer>
    </div>

    <!-- jQuery -->
    <script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/dist/js/adminlte.min.js') }}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/dist/js/demo.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" crossorigin="anonymous">
    </script>
    <script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/plugins/bootstrap/js/bootstrap-notify.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js">
    </script>

    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    <script>
        $('input[type="tel"]').bind("keypress", function(e) {
            var keyCode = e.which ? e.which : e.keyCode
            if (!(keyCode >= 48 && keyCode <= 57)) {
                return false;
            }
        });
    </script>
    <!-- Page specific javascripts-->
    @stack('scripts')
</body>

</html>

resources/views/common/navigation.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('dashboard') }}" class="brand-link">
        <!-- <img src="dist/img/logo.PNG" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" > -->
        <span class="brand-text font-weight-light">
            {{-- <img src="{{ asset('assets/dist/img/logo.PNG') }}" alt="AdminLTE Logo" width="100%"> --}}
            <h4>TASK MANAGEMENT <br>SYSTEM</h4>
        </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        @php
            $user = auth()->user();
        @endphp
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('assets/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2"
                    alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ ucwords(strtolower($user->name)) }}</a>
            </div>
        </div>


        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
                <li class="nav-item menu-open">
                    <a href="{{ route('dashboard') }}"
                        class="{{ request()->is('dashboard*') ? 'nav-link active' : 'nav-link' }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>

                @if ($user->role_id == '1')
                    <li class="nav-item menu-open">
                        <a href="{{ route('supervisor.index') }}"
                            class="{{ request()->is('supervisor*') ? 'nav-link active' : 'nav-link' }}">
                            <i class="nav-icon fas fa-user"></i>
                            <p>
                                Supervisor
                            </p>
                        </a>
                    </li>
                @endif
                @if ($user->role_id == '1' || $user->role_id == '2')
                    <li class="nav-item menu-open">
                        <a href="{{ route('staff.index') }}"
                            class="{{ request()->is('staff*') ? 'nav-link active' : 'nav-link' }}">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                Staff
                            </p>
                        </a>
                    </li>
                @endif
                @if ($user->role_id == '1' || $user->role_id == '2')
                    <li class="nav-item menu-open">
                        <a href="{{ route('client.index') }}"
                            class="{{ request()->is('client*') ? 'nav-link active' : 'nav-link' }}">
                            <i class="nav-icon fas fa-user-circle"></i>
                            <p>
                                Client
                            </p>
                        </a>
                    </li>
                @endif
                @if ($user->role_id == '1')
                    <li class="nav-item menu-open">
                        <a href="{{ route('project.index') }}"
                            class="{{ request()->is('project*') ? 'nav-link active' : 'nav-link' }}">
                            <i class="nav-icon fas fa-project-diagram"></i>
                            <p>
                                Project
                            </p>
                        </a>
                    </li>
                @endif
                @if ($user->role_id == '1' || $user->role_id == '2' || $user->role_id == '3')
                    <li class="nav-item menu-open">
                        <a href="{{ route('task.index') }}"
                            class="{{ request()->is('task*') ? 'nav-link active' : 'nav-link' }}">
                            <i class="nav-icon fas fa-tasks"></i>
                            <p>
                                Task
                            </p>
                        </a>
                    </li>
                @endif

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>